# Generated by Django 6.0.5 on 2026-05-30 20:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa produktu')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.PositiveIntegerField(verbose_name='Zamówiona ilość')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zamówienia')),
                ('status', models.CharField(choices=[('PENDING', 'Oczekujące'), ('COMPLETED', 'Zrealizowane'), ('FAILED', 'Anulowane/Błąd')], default='PENDING', max_length=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Magazyn.product', verbose_name='Produkt')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dostępna ilość')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='Magazyn.product')),
            ],
        ),
    ]
